### PR TITLE
Drop encrypt-blobstore release.

### PR DESCRIPTION
**Pull request by jmcarp**
Because all relevant buckets force encrypted uploads.

### CODE REVIEW

**Comment by rogeruiz** [comment]
Mind if I take the reigns on this button push. This was [my first ☁️.gov contribution](https://github.com/18F/cg-encrypt-blobstore-boshrelease/commit/1e84c714eb9ba56e2a2b72a19455028a5c1a7bd3#commitcomment-17453575) 😁 

Also, what's left on this so it's no longer a `WIP`?

**Comment by jmcarp** [comment]
I just needed to turn on mandatory encryption on the last remaining buckets and fix the issues that came up as a result, which is done now. This should be good to go!

**Review by sharms — APPROVED** [review]

**Comment by LinuxBozo** [comment]
This means we can also mark the boshrelease repo as deprecated and nuke the build pipeline, yeah?

**Comment by jmcarp** [comment]
@LinuxBozo yep!

**Comment by cnelson** [comment]
Sorry @rogeruiz we need to :shipit:

**Pull request merged**
